"""baseline schema

Revision ID: 0001_baseline
Revises: 
Create Date: 2026-09-02 22:54:09.874643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0001_baseline'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('workspaces',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner_email', sa.String(length=320), nullable=True),
    sa.Column('resume_text', sa.Text(), nullable=False),
    sa.Column('resume_filename', sa.String(length=255), nullable=True),
    sa.Column('resume_file', sa.LargeBinary(), nullable=True),
    sa.Column('threshold', sa.Float(), nullable=False),
    sa.Column('auto_apply_threshold', sa.Float(), nullable=False),
    sa.Column('profile_name', sa.String(length=200), nullable=False),
    sa.Column('profile_email', sa.String(length=320), nullable=False),
    sa.Column('profile_phone', sa.String(length=50), nullable=False),
    sa.Column('profile_linkedin', sa.String(length=300), nullable=False),
    sa.Column('profile_portfolio_url', sa.String(length=300), nullable=False),
    sa.Column('profile_github_url', sa.String(length=300), nullable=False),
    sa.Column('profile_city', sa.String(length=100), nullable=False),
    sa.Column('profile_state', sa.String(length=100), nullable=False),
    sa.Column('profile_country', sa.String(length=100), nullable=False),
    sa.Column('profile_location', sa.String(length=200), nullable=False),
    sa.Column('profile_current_company', sa.String(length=200), nullable=False),
    sa.Column('profile_current_title', sa.String(length=200), nullable=False),
    sa.Column('profile_desired_salary', sa.String(length=100), nullable=False),
    sa.Column('profile_start_date', sa.String(length=100), nullable=False),
    sa.Column('profile_work_authorized', sa.String(length=10), nullable=False),
    sa.Column('profile_visa_sponsorship', sa.String(length=10), nullable=False),
    sa.Column('profile_willing_to_relocate', sa.String(length=10), nullable=False),
    sa.Column('profile_18_or_older', sa.String(length=10), nullable=False),
    sa.Column('profile_gender', sa.String(length=100), nullable=False),
    sa.Column('profile_race_ethnicity', sa.String(length=100), nullable=False),
    sa.Column('profile_veteran_status', sa.String(length=100), nullable=False),
    sa.Column('profile_disability_status', sa.String(length=100), nullable=False),
    sa.Column('profile_citizenship', sa.String(length=100), nullable=False),
    sa.Column('profile_security_clearance', sa.String(length=100), nullable=False),
    sa.Column('profile_background_check_consent', sa.String(length=10), nullable=False),
    sa.Column('profile_drug_test_consent', sa.String(length=10), nullable=False),
    sa.Column('profile_criminal_history', sa.String(length=10), nullable=False),
    sa.Column('cover_letter', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_workspaces_owner_email'), ['owner_email'], unique=False)

    op.create_table('batches',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=300), nullable=False),
    sa.Column('days', sa.Integer(), nullable=False),
    sa.Column('max_jobs', sa.Integer(), nullable=False),
    sa.Column('job_title_query', sa.Text(), nullable=False),
    sa.Column('technology_keywords_query', sa.Text(), nullable=False),
    sa.Column('job_description_query', sa.Text(), nullable=False),
    sa.Column('departments', sa.JSON(), nullable=False),
    sa.Column('seniority', sa.JSON(), nullable=False),
    sa.Column('interval_unit', sa.Enum('hour', 'day', 'week', name='batchintervalunit'), nullable=True),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('repeat_mode', sa.Enum('count', 'indefinite', name='batchrepeatmode'), nullable=False),
    sa.Column('run_limit', sa.Integer(), nullable=True),
    sa.Column('runs_completed', sa.Integer(), nullable=False),
    sa.Column('auto_apply_threshold', sa.Float(), nullable=False),
    sa.Column('source', sa.Enum('search', 'upload', name='batchsource'), nullable=False),
    sa.Column('status', sa.Enum('active', 'paused', 'completed', name='batchstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batches_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_batches_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('batch_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('batch_id', sa.Integer(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched', sa.Integer(), nullable=False),
    sa.Column('new', sa.Integer(), nullable=False),
    sa.Column('updated', sa.Integer(), nullable=False),
    sa.Column('auto_applied', sa.Integer(), nullable=False),
    sa.Column('needs_review', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['batch_id'], ['batches.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('batch_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_batch_runs_batch_id'), ['batch_id'], unique=False)

    op.create_table('jobs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('company', sa.String(length=300), nullable=False),
    sa.Column('ats_platform', sa.String(length=80), nullable=False),
    sa.Column('apply_url', sa.Text(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('requirement_coverage', sa.Float(), nullable=False),
    sa.Column('skill_coverage', sa.Float(), nullable=False),
    sa.Column('global_similarity', sa.Float(), nullable=False),
    sa.Column('matched_skills', sa.JSON(), nullable=False),
    sa.Column('missing_skills', sa.JSON(), nullable=False),
    sa.Column('weak_requirements', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('discovered', 'to_apply', 'applied', 'skipped', name='jobstatus'), nullable=False),
    sa.Column('auto_apply_state', sa.String(length=30), nullable=True),
    sa.Column('review_reason', sa.String(length=50), nullable=True),
    sa.Column('last_apply_started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_apply_finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_apply_detail', sa.Text(), nullable=True),
    sa.Column('last_batch_run_id', sa.Integer(), nullable=True),
    sa.Column('source_batch_id', sa.Integer(), nullable=True),
    sa.Column('date_fetched', sa.DateTime(timezone=True), nullable=False),
    sa.Column('date_scored', sa.DateTime(timezone=True), nullable=True),
    sa.Column('date_applied', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['last_batch_run_id'], ['batch_runs.id'], ),
    sa.ForeignKeyConstraint(['source_batch_id'], ['batches.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('workspace_id', 'external_id', name='uq_job_workspace_external')
    )
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_jobs_auto_apply_state'), ['auto_apply_state'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_external_id'), ['external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_source_batch_id'), ['source_batch_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_jobs_workspace_id'), ['workspace_id'], unique=False)

    op.create_table('job_blocked_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('field_type', sa.String(length=20), nullable=False),
    sa.Column('options', sa.JSON(), nullable=False),
    sa.Column('drafted_answer', sa.Text(), nullable=True),
    sa.Column('drafted_by_model', sa.String(length=100), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_id', 'question_text', name='uq_jbq_job_question')
    )
    with op.batch_alter_table('job_blocked_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_job_blocked_questions_job_id'), ['job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_job_blocked_questions_workspace_id'), ['workspace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job_blocked_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_job_blocked_questions_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_job_blocked_questions_job_id'))

    op.drop_table('job_blocked_questions')
    with op.batch_alter_table('jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_jobs_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_jobs_source_batch_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_external_id'))
        batch_op.drop_index(batch_op.f('ix_jobs_auto_apply_state'))

    op.drop_table('jobs')
    with op.batch_alter_table('batch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batch_runs_batch_id'))

    op.drop_table('batch_runs')
    with op.batch_alter_table('batches', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_batches_workspace_id'))
        batch_op.drop_index(batch_op.f('ix_batches_status'))

    op.drop_table('batches')
    with op.batch_alter_table('workspaces', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_workspaces_owner_email'))

    op.drop_table('workspaces')
    op.drop_table('settings')
    # ### end Alembic commands ###
